"""Refresh-safe regeneration of generated artifacts (ADR 0102).

Scrolls' custody contract (`docs/custody-vision.md` §2) is *raw is sacred;
every other surface is a regenerable view*. Compiled `library/` pages and the
generated `agents/` instruction files are exactly such views — rebuilt on every
`scrolls kb` / `scrolls agent install` run. Historically a re-run overwrote the
whole file, so a human or agent who hand-annotated a generated page lost the
note on the next compile.

This module supplies the *mechanism* adapted from obsidian-second-brain's
sentinel-fenced regeneration (mechanism, not its self-mutating-vault
philosophy; see `docs/agents/obsidian-second-brain-inspiration.md`): the
generated content lives between an `@generated` begin marker and an `@end`
marker. A regenerate replaces only that fenced region and is *authoritative*
over it — so stale generated content can never linger — while anything outside
the fence (a `@user` note as a prefix or suffix) is preserved byte-for-byte.

The markers are HTML comments, invisible in rendered Markdown, and the begin
marker self-describes which command regenerates the block. Matching is by a
stable token prefix (`<!-- @generated scrolls` / `<!-- @end scrolls`) so the
human-readable tail can be reworded without orphaning files already on disk.
A file that carries no fence — pre-sentinel output or a fully hand-written
page — has no region to preserve, so the caller overwrites it wholesale, as it
always did.
"""

from __future__ import annotations

from pathlib import Path

# Stable tokens matched at the start of a marker line; the tail after them is
# human-readable prose that may evolve without breaking the parse.
_BEGIN_TOKEN = "<!-- @generated scrolls"
_END_TOKEN = "<!-- @end scrolls"

GENERATED_END = "<!-- @end scrolls -->"


def begin_marker(regenerated_by: str) -> str:
    """The `@generated` begin marker, naming the command that regenerates it."""
    return (
        f"<!-- @generated scrolls — regenerated by `{regenerated_by}`; edits "
        f"inside this block are replaced. Annotate outside the markers (or in a "
        f"separate file) to keep notes. -->"
    )


def fence(body: str, regenerated_by: str) -> str:
    """Wrap `body` in the sentinel fence, trailing newline included."""
    return f"{begin_marker(regenerated_by)}\n{body}\n{GENERATED_END}\n"


def _fence_spans(lines: list[str]) -> list[tuple[int, int]]:
    """The (begin, end) line indices of every well-formed fence, in order.

    Each `@generated` line pairs with the first `@end` line after it; the scan
    then resumes past that `@end`, so a file with several sibling fences (the
    shareable custody bundle's items + custody-events blocks, roadmap H67) yields
    one span per region. A dangling `@generated` with no matching `@end` is not a
    region and is dropped.
    """
    spans: list[tuple[int, int]] = []
    begin: int | None = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if begin is None and stripped.startswith(_BEGIN_TOKEN):
            begin = i
        elif begin is not None and stripped.startswith(_END_TOKEN):
            spans.append((begin, i))
            begin = None
    return spans


def _fence_span(lines: list[str]) -> tuple[int, int] | None:
    """The (begin, end) line indices of the first well-formed fence, or None.

    The first `@generated` line and the first `@end` line after it delimit the
    region; a text missing either carries no fence. The single-region API the
    compiled `library/`/`agents/` pages use (each carries exactly one fence).
    """
    spans = _fence_spans(lines)
    return spans[0] if spans else None


def user_regions(text: str) -> tuple[str, str] | None:
    """Split `text` into the (prefix, suffix) user regions around the fence.

    Returns the bytes before the `@generated` marker line and after the `@end`
    marker line — the spans a regenerate must preserve — or ``None`` when the
    text carries no well-formed fence (a pre-sentinel or hand-written file the
    caller should overwrite wholesale).
    """
    lines = text.splitlines(keepends=True)
    span = _fence_span(lines)
    if span is None:
        return None
    begin, end = span
    return "".join(lines[:begin]), "".join(lines[end + 1 :])


def generated_body(text: str) -> str | None:
    """The content inside the fence, or ``None`` when the text carries no fence.

    The inverse of `user_regions`: where that returns the spans outside the
    fence, this returns the regenerated span between the markers — useful for
    inspecting (or asserting on) a page's generated shape without its sentinel
    wrapper. Round-trips with `fence`: ``generated_body(fence(b, by)) == b + "\\n"``.
    """
    lines = text.splitlines(keepends=True)
    span = _fence_span(lines)
    if span is None:
        return None
    begin, end = span
    return "".join(lines[begin + 1 : end])


def generated_bodies(text: str) -> list[str]:
    """The content inside every fence, in order — the multi-region reader.

    The plural of `generated_body`: where that returns the first fenced region,
    this returns one body per `@generated`…`@end` region. The shareable custody
    bundle (roadmap H67) carries two sibling regions — the lossless items block
    and the custody-events block — so an importer reads ``[0]`` for items and
    ``[1]`` for events; a pre-H67 bundle with only the items block yields a
    one-element list, so the events reader sees no second region (events simply
    do not travel, the prior behavior). The single-fence callers
    (`user_regions`/`generated_body`/`splice`) are unaffected: a compiled page
    carries exactly one fence, so they keep operating on the first region.
    """
    lines = text.splitlines(keepends=True)
    return ["".join(lines[begin + 1 : end]) for begin, end in _fence_spans(lines)]


def has_user_content(text: str) -> bool:
    """Whether a generated page carries a non-empty annotation outside its fence."""
    regions = user_regions(text)
    return regions is not None and bool(regions[0].strip() or regions[1].strip())


def splice(
    existing: str | None, body: str, regenerated_by: str, *, header: str = ""
) -> str:
    """Render `body` into the fence, preserving any user regions of `existing`.

    With no prior file (or a marker-less one) this is just ``header + fence(body)``;
    with a fenced prior file the prefix and suffix user regions are spliced back
    unchanged around the freshly generated region.

    `header` is generated content that must stay at the very top of the file —
    YAML frontmatter, whose `---` has to be byte 0 for a skill page to parse
    (`scrolls agent install`). It is *always* regenerated, so when a header is
    given the region before the fence is treated as a stale header, not a user
    prefix: the fresh header replaces it and only the suffix after `@end` is
    preserved. With the default empty header both user regions are kept, as the
    compiled `library/` pages need (their content can be annotated either side).
    """
    regions = user_regions(existing) if existing is not None else None
    prefix, suffix = regions if regions is not None else ("", "")
    if header:
        prefix = header
    return f"{prefix}{fence(body, regenerated_by)}{suffix}"


def write_generated(
    path: Path, body: str, regenerated_by: str, *, header: str = ""
) -> None:
    """Write a generated page at `path`, preserving its user regions (ADR 0102).

    Reads any existing file first so a hand annotation outside the fence
    survives, then writes the spliced result. `body` is the fresh generated
    content with no wrapping fence or trailing newline. `header`, when given, is
    a regenerated header pinned above the fence (see `splice`).
    """
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        splice(existing, body, regenerated_by, header=header), encoding="utf-8"
    )
